### ISSUE TITLE
PythonEnvy doesn't seem to bode well with ipynb files

### ISSUE THREAD

**Issue by KristianMischke** [teticio/python-envy#2]
When I have PythonEnvy enabled, I am unable to navigate to the source code of imports in an `.ipynb`. Disabling the extension allows me to properly navigate to the source code.

Is there a way to disable PythonEnvy for notebooks?

**Comment by teticio** [comment]
To understand, in your project which is the python virtual environment that the notebook is using? Is it in a .venv somewhere along the path where the notebook is? If so, I will try to reproduce it.

**Comment by teticio** [comment]
I'm also not sure what you mean by "naviagte to". Do you mean right mouse button "go to definition"? This doesn't work very well for me with or without Python Envy enabled: it takes me to my user package directory, not the one used by the kernel. Or do you mean when you hit an error and click on the stack trace (because that works just fine for me).

Python Envy only sets the Python interpreter and not the kernel of any notebooks. Only issue I can think of is that, if you are running the notebooks from VSCode (which I assume you are), then you need to have `jupyter` and `ipykernel` installed in the `.venv` that is activated by Python Envy when you click on the notebook.
